
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Astronaut(props) {
  const { nodes, materials } = useGLTF('/models/cosmonauts_toy.glb')

  return (
    <group {...props} dispose={null}>
      <group
        rotation={[-Math.PI / 2, -0.2, 2.2]}
        scale={props.scale || 0.3}>
        <group
          position={[1.3, -1, 0]}
          >
          
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_Material001_0.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_Material006_0.geometry}
            material={materials['Material.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_Material002_0.geometry}
            material={materials['Material.002']}
          />
        </group>
        <group
          position={[1.244, -62.085, -24.139]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[17.521, 19.077, 23.266]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.food_Material001_0.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.food_Material003_0.geometry}
            material={materials['Material.003']}
          />
        </group>
        <group position={[4.428, -9.121, -42.489]} rotation={[-1.801, 0, 0.061]} scale={138.279}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ruki_Material019_0.geometry}
            material={materials['Material.019']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ruki_Material001_0.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ruki_Material018_0.geometry}
            material={materials['Material.018']}
          />
        </group>
        <group
          position={[1.244, -62.085, 24.139]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[17.521, 19.077, 23.266]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.food001_Material001_0.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.food001_Material003_0.geometry}
            material={materials['Material.003']}
          />
        </group>
        <group position={[5.793, -9.541, 64.502]} rotation={[-1.801, 0, 0.061]} scale={138.279}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ruki001_Material019_0.geometry}
            material={materials['Material.019']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ruki001_Material001_0.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ruki001_Material018_0.geometry}
            material={materials['Material.018']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Material003_0.geometry}
          material={materials['Material.003']}
          position={[0.459, -43.865, -24.585]}
          rotation={[-0.841, 0, 0]}
          scale={[17.711, 19.881, 19.612]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/cosmonauts_toy.glb')
